name: React Base
on: ["workflow_dispatch", "push"]

jobs:
  test-git:
    runs-on: ubuntu-latest
    steps:
       - name: testls
         run: ls      
  build-app:
       runs-on: ubuntu-latest
       steps:
         - name: Get sources files
           uses: actions/checkout@v6
         - name: Install dependencies
           run: npm ci
         - name: Build app
           run: npm run build
         - name: Test build completion
           run: ls dist/index.html 